steps:
  # Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-app:$_IMAGE_TAG'
      - '.'

  # Dockerイメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-app:$_IMAGE_TAG'

  # Cloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'todo-app'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-app:$_IMAGE_TAG'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,MONGODB_URI=mongodb+srv://todoapp_db_user:dRmuKSk97u0fS91l@todo-app-cluster.wsrcrk9.mongodb.net/todo-app?appName=todo-app-cluster'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'
      - '--timeout'
      - '300'

images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/todo-app-repo/todo-app:$_IMAGE_TAG'

substitutions:
  _IMAGE_TAG: 'latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
